{{- if .Values.events.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: crowler-events
  labels:
    app.kubernetes.io/name: crowler-events
    {{- include "thecrowler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.events.service.type }}
  selector:
    app.kubernetes.io/name: crowler-events
  ports:
    - name: http
      port: {{ .Values.events.service.port }}
      targetPort: http
{{- end }}
