{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thecrowler.secretName" . }}
  labels:
    {{- include "thecrowler.labels" . | nindent 4 }}
type: Opaque
stringData:
  DOCKER_POSTGRES_PASSWORD: {{ .Values.secrets.data.postgresPassword | quote }}
  DOCKER_CROWLER_DB_USER: {{ .Values.secrets.data.crowlerDbUser | quote }}
  DOCKER_CROWLER_DB_PASSWORD: {{ .Values.secrets.data.crowlerDbPassword | quote }}
{{- end }}
