apiVersion: v1
kind: Service
metadata:
  name: crowler-db-headless
  namespace: crowler
  labels:
    app.kubernetes.io/name: crowler-db
    app.kubernetes.io/part-of: thecrowler
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: crowler-db
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
