apiVersion: v1
kind: Service
metadata:
  name: crowler-events
  namespace: crowler
  labels:
    app.kubernetes.io/name: crowler-events
    app.kubernetes.io/part-of: thecrowler
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: crowler-events
  ports:
    - name: http
      port: 8082
      targetPort: http
