apiVersion: v1
kind: Service
metadata:
  name: crowler-vdi
  namespace: crowler
  labels:
    app.kubernetes.io/name: crowler-vdi
    app.kubernetes.io/part-of: thecrowler
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app.kubernetes.io/name: crowler-vdi
  ports:
    - name: selenium
      port: 4444
      targetPort: selenium
    - name: management
      port: 4445
      targetPort: management
    - name: vnc
      port: 5900
      targetPort: vnc
    - name: novnc
      port: 7900
      targetPort: novnc
    - name: cdp
      port: 9222
      targetPort: cdp
