apiVersion: v1
kind: Service
metadata:
  name: crowler-jaeger
  namespace: crowler
  labels:
    app.kubernetes.io/name: crowler-jaeger
    app.kubernetes.io/part-of: thecrowler
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: crowler-jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: ui
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
