apiVersion: v1
kind: Service
metadata:
  name: crowler-api
  namespace: crowler
  labels:
    app.kubernetes.io/name: crowler-api
    app.kubernetes.io/part-of: thecrowler
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: crowler-api
  ports:
    - name: http
      port: 8080
      targetPort: http
